### ISSUE TITLE
Connection string

### ISSUE THREAD

**Issue by nunomaia** [nunomaia/NwRfcNet#1]
The connection to include the server name, and other parameters needed to establish the initial connection.

**Comment by sommedig** [comment]
Does the connector support Single Sign On - (SSO) options?

**Comment by nunomaia** [comment]
NW RFC Library 7.5 supports SSO by defining snc_qop, snc_myname, snc_partnername and snc_lib  connection values. These properties aren’t exposed in NwRfcNet since is difficult to test SSO scenarios.  

Are you using Kerberos authentication in an Active Directory environment ?

**Comment by sommedig** [comment]
Yes, by default were using Kerberos authentication

**Comment by nunomaia** [comment]
I have opened a new issue to follow up SSO #29. I have made a small test and it is possible to use SSO. I will upload tomorrow a change.
#29

**Comment by sommedig** [comment]
Thank you!

**Comment by nunomaia** [comment]
SSO connection exposed and documented in Readme

**Comment by sommedig** [comment]
Thanks, tested it out and it works!
