### ISSUE TITLE
Suggestion: Associate RfcMapper with RfcFunction rather than RfcConnection

### ISSUE THREAD

**Issue by cjbailey** [nunomaia/NwRfcNet#28]
This is just an idea (and you might have reason for not doing things this way), but in my mind it seems more logical to associate the mapper with a specific RfcFunction rather than the RfcConnection, so multiple mappers would be used where multiple function calls are required, rather than a single generic RfcConnection.Mapper (RfcFunction.DefaultMapper).

**Comment by cjbailey** [comment]
p.s. maybe a better place for suggestions/discussions would be https://gitter.im??

**Comment by nunomaia** [comment]
You can set the mapper at RFC function.

After creating the RFC function define the property Mapper.

var f = funconn.CallRfcFunction("BAPI_COMPANYCODE_GETLIST")
f.Mapper = …

I don’t see an advantage for now of moving discussions to gitter.

**Comment by cjbailey** [comment]
I can't see the Mapper property on RfcFunction... only RfcConnection, so your suggestion wouldn't work, unless I'm missing something?!?

**Comment by nunomaia** [comment]
Sorry, I have update a new version to expose this feature. That functionality was in a private branch. 
Check Version 0.0.4

**Comment by cjbailey** [comment]
Awesome, thanks!  And great work with NwRfcNet by the way.  :)

**Comment by nunomaia** [comment]
Thanks :-)
