### ISSUE TITLE
Date Mapping Bug

### ISSUE THREAD

**Issue by sommedig** [nunomaia/NwRfcNet#33]
I'm calling a rfc function with the Date input parameter. I'm mapping the value as a RFC date object.

I've tried changing the .Net object from DateTime, string, & tried adding different max lengths to the abap object.  All of these get the same error:

![image](https://user-images.githubusercontent.com/44176420/68889847-be6b3680-06eb-11ea-829f-5e6e9f1ec129.png)

**Comment by nunomaia** [comment]
Can you provide a sample of your code ?

**Comment by sommedig** [comment]
Upgraded nugget package from vs 6 to 7 which resolved this issue. Closing out..
